### ISSUE TITLE
Global Temporary Table Issue

### ISSUE THREAD

**Issue by webstackz** [yajra/laravel-oci8#434] opened 2018-06-05 18:44 UTC
--- Global Temporary Table ----    
CREATE GLOBAL TEMPORARY TABLE "SYSTEM"."GTT_TABLES" 
   (    "ID" NUMBER(10,0) NOT NULL ENABLE, 
    "FIRSTNAME" VARCHAR2(191 BYTE), 
    "LASTNAME" VARCHAR2(191 BYTE), 
    "EMAIL" VARCHAR2(191 BYTE), 
    "POINTS" VARCHAR2(191 BYTE), 
    "NOTES" VARCHAR2(191 BYTE), 
    "CREATED_AT" TIMESTAMP (6), 
    "UPDATED_AT" TIMESTAMP (6), 
    "AGE" NUMBER(10,0), 
    "JOB" VARCHAR2(191 BYTE), 
    "GENDER" VARCHAR2(191 BYTE), 
    "COUNTRY" VARCHAR2(191 BYTE), 
    "SALE_DATE" VARCHAR2(191 BYTE)
   ) ON COMMIT PRESERVE ROWS ;  

--- PROCEDURE -----            
create or replace PROCEDURE PR_TEST  AS
BEGIN
DELETE GTT_TABLED;  
INSERT INTO GTT_TABLES (SELECT * FROM DATATABLES);
COMMIT;
END;

Php(7.2.1)(persistent) and oracle (12c) Global temporary table Issue.Some Times Data Cannot Get Returns Empty Table.This Issue Only In Global Temporary Table.

**Comment by yajra** [comment] 2018-06-07 03:03
Not sure on this but maybe you should specify the system schema on your procedure?

```sql
create or replace PROCEDURE PR_TEST AS
BEGIN
DELETE SYSTEM.GTT_TABLED;
INSERT INTO SYSTEM.GTT_TABLES (SELECT * FROM DATATABLES);
COMMIT;
END;
```

**Comment by webzdevz** [comment] 2018-06-07 05:28
Its An Example and Typing Mistake Too.

--- Global Temporary Table ----    
CREATE GLOBAL TEMPORARY TABLE "GSFIN"."GTT_TABLES" 
   (    "ID" NUMBER(10,0) NOT NULL ENABLE, 
    "FIRSTNAME" VARCHAR2(191 BYTE), 
    "LASTNAME" VARCHAR2(191 BYTE), 
    "EMAIL" VARCHAR2(191 BYTE), 
    "POINTS" VARCHAR2(191 BYTE), 
    "NOTES" VARCHAR2(191 BYTE), 
    "CREATED_AT" TIMESTAMP (6), 
    "UPDATED_AT" TIMESTAMP (6), 
    "AGE" NUMBER(10,0), 
    "JOB" VARCHAR2(191 BYTE), 
    "GENDER" VARCHAR2(191 BYTE), 
    "COUNTRY" VARCHAR2(191 BYTE), 
    "SALE_DATE" VARCHAR2(191 BYTE)
   ) ON COMMIT PRESERVE ROWS ;  

--- PROCEDURE -----            
create or replace PROCEDURE PR_TEST  AS
BEGIN
DELETE GSFIN.GTT_TABLES;  
INSERT INTO GSFIN.GTT_TABLES (SELECT * FROM GSFIN.DATATABLES);
COMMIT;
END;

https://stackoverflow.com/questions/50613573/php-oracle-global-temporary-table

**Comment by webzdevz** [comment] 2018-06-07 05:36
I Checked In Schema,Oracle Connection Type (POOLED, RESERVED, SHARED) And Faced Same Problems in Codeigniter , Php , Jsp.
Finally, I Stuck In Global Temporary Table.
Above The Issue Is Without Using Php Artisan serve.
Using Php Artisan same date il be shown In all ip.
Plz Give Perfect Solution for me.

**Closed** 2021-04-10 09:41 UTC
