### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by junitobermudez** [yajra/laravel-oci8#662] opened 2021-07-08 15:54 UTC
### Summary of problem or feature request

I am trying to use a secondary connection with the oracle connection and receiving an error when trying to connect to the database. I receive the following error.

Trying to access array offset on value of type bool

The error is happening at vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8.php:142

The code that this is happenign at is:
throw new Oci8Exception($e['message'], $e['code']);

**Comment by abrahampe** [comment] 2021-07-27 20:46
I am receiving this error too. My PHP version is PHP 7.4.6 (cli) ( NTS ) running on SUSE Linux Enterprise Server 15 SP2  (x86_64)  with yajra/laravel-oci8 (v6.1.3)

**Comment by yajra** [comment] 2021-09-18 02:31
Can you please provide some snippets to reproduce the issue?

**Comment by Soorajabbasi** [comment] 2021-10-04 14:56
I am facing same issue with my application using php 7.4.19

**Comment by cysunshine** [comment] 2021-11-09 13:21
I have the same issue:
php 7.4.6 (Thread safe)
Trying to access array offset on value of type bool 
@file:C:\web\www\autoworks\vendor\yajra\laravel-pdo-via-oci8\src\Pdo\Oci8.php @line:478

**Comment by blackdrago** [comment] 2022-04-24 22:58
This is occurring for me at line 478 as well. This is because `oci_error()` is returning `false` instead of an error message. From what I understand, it only returns `false` when no error exists/is available. 

Any successful OCI statement can clear the error, so if `oci_error()` isn't immediately called, it is possible that a successful statement is somehow clearing the error first. But I don't think that applies here.

This is the code that immediate precedes the statement:
```php
        $sessionMode = array_key_exists('session_mode', $options) ? $options['session_mode'] : null;

        if (array_key_exists(PDO::ATTR_PERSISTENT, $options) && $options[PDO::ATTR_PERSISTENT]) {
            $this->dbh = @oci_pconnect($username, $password, $dsn, $charset, $sessionMode);
        } else {
            $this->dbh = @oci_connect($username, $password, $dsn, $charset, $sessionMode);
        }

        if (! $this->dbh) {
            $e = oci_error();
            throw new Oci8Exception($e['message'], $e['code']);
        }
```

Is it possible that `$this->dbh` may be empty without an error existing? My understanding is that the `@` prefix will prevent an error message from being created. Could that be a factor?

I also wanted to add: this error occurs because of a connectivity issue with the database. As best as I can tell, the code is throwing this error because it encountered an error when trying to connect. So if you're experiencing this, you should investigate your database connection/network activity/VPN/whatever else might be at play here.

**Comment by yajra** [comment] 2022-12-21 08:08
Related PR https://github.com/yajra/pdo-via-oci8/pull/121

**Comment by yajra** [comment] 2022-12-21 08:46
Fixed via https://github.com/yajra/pdo-via-oci8/pull/121

**Closed by yajra** 2022-12-21 08:46 UTC
Labels: can't reproduce
