### ISSUE TITLE
Use of undefined constant OCI_CRED_EXT - assumed 'OCI_CRED_EXT' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by muhghazaliakbar** [yajra/laravel-oci8#506] opened 2019-05-11 08:49 UTC
### Summary of problem or feature request

I'm having error when trying to select table. Anyone can help?

### Code snippet of problem
```php
Route::get('test-oracle-connection', function () {
    $sspd = \Illuminate\Support\Facades\DB::connection('oracle')->table('sspd')->first();

    dd($sspd);
});
```
Errors:
```
Use of undefined constant OCI_CRED_EXT - assumed 'OCI_CRED_EXT' (this will throw an Error in a future version of PHP)
```

### System details
- Operating System: `macOS Mojave Version 10.14.4 (18E226)`
- PHP Version: `7.3`
- Laravel Version: `5.8.*`
- Laravel-OCI8 Version: `5.8.*`

**Comment by anugrahdputra** [comment] 2019-05-14 03:58
i got same problem

**Comment by muhghazaliakbar** [comment] 2019-05-14 05:47
@anugrahdputra Did you figured out?

**Comment by yajra** [comment] 2019-05-14 06:31
@muhghazaliakbar can you please provide the table's migration? Working fine on my side using the `users` table.

```
   tinker
Psy Shell v0.9.9 (PHP 7.1.26 — cli) by Justin Hileman
>>> DB::table('users')->first();
=> {#4125
     +"id": "1",
     +"first_name": "CMS",
     +"last_name": "Administrator",
     +"email": "admin@example.com",
     +"email_verified_at": null,
     +"is_activated": "1",
     +"is_blocked": "0",
     +"password": "$2y$10$F8GAwF/tAl6HWDvxxvqDDOkGstYvV8jmahvPbI3bRc.54U821qfeK",
     +"avatar": null,
     +"parameters": null,
     +"is_admin": "1",
     +"remember_token": "hkx4oIZ4MP",
     +"verification_token": null,
     +"deleted_at": null,
     +"created_by": "0",
     +"updated_by": "0",
     +"created_at": "2019-05-09 02:33:36",
     +"updated_at": "2019-05-09 02:33:36",
   }
>>>
```

**Comment by anugrahdputra** [comment] 2019-05-14 06:41
**Code snippet of problem**
`$data = DB::connection('oracle')->select('SELECT * FROM SW_DB WHERE ROWNUM = 1')`

It working fine with tinker, but doesn't work from laravel controller and give error 
`Use of undefined constant OCI_CRED_EXT - assumed 'OCI_CRED_EXT' (this will throw an Error in a future version of PHP)`

**Comment by yajra** [comment] 2019-05-14 07:02
Still working for me. There might be something odd on your table which may cause the issue?

```php
Route::get('/', function () {
    dump(DB::select('select * from users where rownum=1'));
    dd(DB::table('users')->first());
});
```

```
array:1 [▼
  0 => {#1369 ▼
    +"id": "1"
    +"first_name": "CMS"
    +"last_name": "Administrator"
    +"email": "admin@example.com"
    +"email_verified_at": null
    +"is_activated": "1"
    +"is_blocked": "0"
    +"password": "$2y$10$F8GAwF/tAl6HWDvxxvqDDOkGstYvV8jmahvPbI3bRc.54U821qfeK"
    +"avatar": null
    +"parameters": null
    +"is_admin": "1"
    +"remember_token": "hkx4oIZ4MP"
    +"verification_token": null
    +"deleted_at": null
    +"created_by": "0"
    +"updated_by": "0"
    +"created_at": "2019-05-09 02:33:36"
    +"updated_at": "2019-05-09 02:33:36"
  }
]
{#1375 ▼
  +"id": "1"
  +"first_name": "CMS"
  +"last_name": "Administrator"
  +"email": "admin@example.com"
  +"email_verified_at": null
  +"is_activated": "1"
  +"is_blocked": "0"
  +"password": "$2y$10$F8GAwF/tAl6HWDvxxvqDDOkGstYvV8jmahvPbI3bRc.54U821qfeK"
  +"avatar": null
  +"parameters": null
  +"is_admin": "1"
  +"remember_token": "hkx4oIZ4MP"
  +"verification_token": null
  +"deleted_at": null
  +"created_by": "0"
  +"updated_by": "0"
  +"created_at": "2019-05-09 02:33:36"
  +"updated_at": "2019-05-09 02:33:36"
}
```

**Comment by anugrahdputra** [comment] 2019-05-15 01:06
@yajra thank you, my problem has been solved. yesterday an error occurred because I used `php7.3` on the ubuntu setting but php apache2 still uses `php7.2`

**Comment by muhghazaliakbar** [comment] 2019-05-23 03:38
@anugrahdputra @yajra Can you show me your .env config please?

**Comment by ascali** [comment] 2019-05-23 05:00
@yajra Hi,
Currently I have an issue like that.
what's wrong with the query ? 
previously there is no error with my query, looks normal.
what causes deprecated program code
sorry my bad english

**Comment by anugrahdputra** [comment] 2019-05-23 06:00
@muhghazaliakbar My problem yesterday was not Laravel or Laravel-Oci8, but a problem with PHP settings. But this is my .env config

```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:Tk2Z9C8vuQ9FHqDJhAYutvTQixdzl9FBkzblfXD4YA0=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=jr_laravel_oracle
DB_USERNAME=root
DB_PASSWORD=

ORACLE_CONNECTION=oraview
ORACLE_HOST=172.16.10.8
ORACLE_PORT=3334
ORACLE_DATABASE=JR
ORACLE_USERNAME=JR_USER
ORACLE_PASSWORD=p4$$w0rD

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```

**Comment by ascali** [comment] 2019-05-23 06:11
> @muhghazaliakbar My problem yesterday was not Laravel or Laravel-Oci8, but a problem with PHP settings. But this is my .env config
> 
> ```
> APP_NAME=Laravel
> APP_ENV=local
> APP_KEY=base64:Tk2Z9C8vuQ9FHqDJhAYutvTQixdzl9FBkzblfXD4YA0=
> APP_DEBUG=true
> APP_URL=http://localhost
> 
> LOG_CHANNEL=stack
> 
> DB_CONNECTION=mysql
> DB_HOST=127.0.0.1
> DB_PORT=3306
> DB_DATABASE=jr_laravel_oracle
> DB_USERNAME=root
> DB_PASSWORD=
> 
> ORACLE_CONNECTION=oraview
> ORACLE_HOST=172.16.10.8
> ORACLE_PORT=3334
> ORACLE_DATABASE=JR
> ORACLE_USERNAME=JR_USER
> ORACLE_PASSWORD=p4$$w0rD
> 
> BROADCAST_DRIVER=log
> CACHE_DRIVER=file
> QUEUE_CONNECTION=sync
> SESSION_DRIVER=file
> SESSION_LIFETIME=120
> 
> REDIS_HOST=127.0.0.1
> REDIS_PASSWORD=null
> REDIS_PORT=6379
> 
> MAIL_DRIVER=smtp
> MAIL_HOST=smtp.mailtrap.io
> MAIL_PORT=2525
> MAIL_USERNAME=null
> MAIL_PASSWORD=null
> MAIL_ENCRYPTION=null
> 
> PUSHER_APP_ID=
> PUSHER_APP_KEY=
> PUSHER_APP_SECRET=
> PUSHER_APP_CLUSTER=mt1
> 
> MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
> MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
> ```

Here my .env set up for oracle
DBDRKOUTEI_CONNECTION=oracle
DBDRKOUTEI_HOST=koutei-server
DBDRKOUTEI_HOSTIPL=192.168.1.5
DBDRKOUTEI_PORT=1521
DBDRKOUTEI_SID=orcl
DBDRKOUTEI_USERNAME=doctor_pro_data
DBDRKOUTEI_PASSWORD=doctor
DBDRKOUTEI_DATABASE=Dr.Koutei

hope this help you @anugrahdputra

**Comment by ascali** [comment] 2019-05-25 01:34
Hi @yajra please help me, 
I stuck with that error  , any clue for that ?
I have searched for it on stackoverflow and google, but still haven't found the answer.

Here is the source code that I wrote in Lumen 5.8.*: 
    $dr_koutei = DB::connection('xxxxx');
    $current_month = date('m-Y');
    $proses = $dr_koutei->select("
      SELECT cstmr_cd, COUNT(*) AS count_mold
      FROM t_jobno 
      WHERE TO_CHAR(PROC_DEADLINE, 'MM-YYYY') = '$current_month' AND cstmr_cd IS NOT NULL
      AND MFGNO NOT IN ( 'P-KYI-2dp RA Fix', 'TES', 'Contoh Try Sample', 'Z-KAIZEN', 'OTHER', 'SIMUL-G300TAC-B2', 'SIMUL-P-ACC-946F CC', 'KYI XXX', 'P-AAC-XXX' )
      GROUP BY cstmr_cd ORDER BY cstmr_cd ASC
    ");
    if ($proses!==null){
      return responses(1,'',$proses,200);
    }else{
      return responses(0,'Gagal mengambil data',[],404);
    } 
.

and some logs: 
Use of undefined constant OCI_CRED_EXT - assumed 'OCI_CRED_EXT' (this will throw an Error in a future version of PHP)
in OracleConnector.php line 41
at Application->Laravel\Lumen\Concerns\{closure}(2, 'Use of undefined constant OCI_CRED_EXT - assumed \'OCI_CRED_EXT\' (this will throw an Error in a future version of PHP)', 'C:\\inetpub\\wwwroot\\fusion\\dashboard_meiwa_api\\vendor\\yajra\\laravel-oci8\\src\\Oci8\\Connectors\\OracleConnector.php', 41,array('config' => array('driver' => 'oracle', 'host' => '192.168.1.xxx', 'port' => '1521', 'database' => 'xxxxxx', 'service_name' => 'orcl', 'username' => 'xxxxxx, 'password' => 'xxxxx', 'charset' => 'AL32UTF8', 'prefix' => '', 'strict' => false, 'name' => 'xxxx'), 'tns' => '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.xxx)(PORT = 1521)) (CONNECT_DATA =(SERVICE_NAME = orcl)))', 'options' => array(2, 2, 0)))in OracleConnector.php line 41

The actions I have taken:
1. I previously run on a standalone php server (php 7.25)
2. then I move to the iis server with php 7.25

The version in composer I use today is 
    "require": {
        "php": ">=7.2.5",
        "laravel/lumen-framework": "5.8.*",
        "vlucas/phpdotenv": "^3.3",
        "staudenmeir/eloquent-param-limit-fix": "^1.0",
        "yajra/laravel-oci8": "5.8.*"
    },

**Comment by yajra** [comment] 2019-05-25 01:46
@ascali are you using Windows OS? It seems like OCI_CRED_EXT is not supporting it. 

https://www.php.net/manual/en/function.oci-connect.php

# session_mode
> This parameter is available since version PHP 5 (PECL OCI8 1.1) and accepts the following values: OCI_DEFAULT, OCI_SYSOPER and OCI_SYSDBA. If either OCI_SYSOPER or OCI_SYSDBA were specified, this function will try to establish privileged connection using external credentials. Privileged connections are disabled by default. To enable them you need to set oci8.privileged_connect to On.

> PHP 5.3 (PECL OCI8 1.3.4) introduced the OCI_CRED_EXT mode value. This tells Oracle to use External or OS authentication, which must be configured in the database. The OCI_CRED_EXT flag can only be used with username of "/" and a empty password. oci8.privileged_connect may be On or Off.

> OCI_CRED_EXT may be combined with the OCI_SYSOPER or OCI_SYSDBA modes.

> OCI_CRED_EXT is not supported on Windows for security reasons.

This was introduced on #474. Reviewing a possible fix. If you can, please do not hesitate to submit a PR for a fix.

**Comment by yajra** [comment] 2019-05-25 01:58
Maybe suppressing the error might fix the issue? Can you please try the code below. Or maybe a try catch? It's working on my side so I can't reproduce the issue.

```php
//  OracleConnector.php

        if (@array_get($options, 'session_mode') === OCI_CRED_EXT) {
            // External connections can only be used with user / and an empty password
            $config['username'] = '/';
            $config['password'] = null;
        }
```

**Comment by ascali** [comment] 2019-05-25 02:17
> Maybe suppressing the error might fix the issue? Can you please try the code below. Or maybe a try catch? It's working on my side so I can't reproduce the issue.
> 
> ```
> //  OracleConnector.php
> 
>         if (@array_get($options, 'session_mode') === OCI_CRED_EXT) {
>             // External connections can only be used with user / and an empty password
>             $config['username'] = '/';
>             $config['password'] = null;
>         }
> ```
@yajra I changed my code with yours and try what you suggest but there was no change, with the same error.
Actualy I have tried to reproduce the error on another server, but that error didn't appear.
I'm confused, is it wrong from the library or from my code or else, ..

**Comment by yajra** [comment] 2019-05-25 02:19
It's not a problem with the package but on PHP settings as per @anugrahdputra confirmation. But I am not sure what settings needs to be adjusted.

**Comment by ascali** [comment] 2019-05-25 02:25
> It's not a problem with the package but on PHP settings as per @anugrahdputra confirmation. But I am not sure what settings needs to be adjusted.

I think my settings is fine because previously run normal there is no error, do you have any recomendation about it..

**Comment by CodinMoldovanu** [comment] 2019-06-04 11:02
Also confronted with this. Tinker works without issue but running code inside a Controller greets me with the same error as above.

**Comment by yajra** [comment] 2019-06-07 01:11
Unfortunately, I can't replicate the issue and not really sure how to fix this. If anyone finds a solution, please do not hesitate to submit a PR. Thanks!

**Comment by CodinMoldovanu** [comment] 2019-06-07 06:30
Ok, the issue was not in PHP per se but in configuration of the instant client for Oracle. 
There's $LD_LIBRARY_PATH and $ORACLE_HOME environment variables which should both point to the path of the instant client.

**Comment by mdemori** [comment] 2019-08-06 15:56
Hello, 
I just had the same problem, after one our of testing I found that I forgot to activate the oci8 module on fpm.
I just activated it for CLI so, tinker work but I receive the error message inside a controller of my web application.

Activating the module on fpm has fixed the problem for me.

**Comment by wjgray99** [comment] 2019-08-20 14:12
I recently hit upon this issue and was able to resolve it.  I came across the problem while updating PHP.  The only resolution I've found thus far is to ensure that you are on 64 bit everything (Apache, PHP, AND Oracle Instant Client).  Also, be sure to point your Apache (64-bit!) to the correct PHP (64-bit) in httpd.conf.  Make sure the 64 bit Instant Client is on your path!  Once all the pieces were in the right place... voila.   

That undefined constant's value is HUGELY negative (> 32-bit).

Hope this helps!

**Comment by wjgray99** [comment] 2019-08-20 14:16
> Unfortunately, I can't replicate the issue and not really sure how to fix this. If anyone finds a solution, please do not hesitate to submit a PR. Thanks!

Yajra... simply put a 32-bit instant client ahead in the path rather than a 32 bit and you will see this error.

**Comment by JPdiedhiou** [comment] 2019-10-18 19:22
Hi i'm trying to make a seeder but when i run the command: php artisan make:seed 
i get this errors i need help for to progress.....

 ErrorException  : Use of undefined constant users - assumed 'users' (this will throw an Error in a future version of PHP)

  at /home/jp/Laravel-projects/Messagerie_version_1.0/database/seeds/UsersTableSeeder.php:15
    11|      */
    12|     public function run()
    13|     {
    14|         for($i = 0; $i < 10; $i++){
  > 15|             \Illuminate\Support\Facades\DB::table(users)->insert([
    16|                 'name'=> "Ghostman$i",
    17|                 'email'=> "ghost$i@man.sn",
    18|                 "password"=> bcrypt('0000')
    19|             ]);

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Use of undefined constant users - assumed 'users' (this will throw an Error in a future version of PHP)", "/home/jp/Laravel-projects/Messagerie_version_1.0/database/seeds/UsersTableSeeder.php", [])
      /home/jp/Laravel-projects/Messagerie_version_1.0/database/seeds/UsersTableSeeder.php:15

  2   UsersTableSeeder::run()
      /home/jp/Laravel-projects/Messagerie_version_1.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  Please use the argument -v to see more details.

**Comment by CodinMoldovanu** [comment] 2019-10-26 23:54
@JPdiedhiou you need to use quotes on the table name like so `DB::table('table_name')`

@yajra can this issue be closed since it was identified that the issue lies in the system configuration? Maybe a change in documentation to be a bit more verbose about the instantclient will solve future issues. Will try to compile some resources and help with this.

**Comment by yajra** [comment] 2019-11-05 01:56
I just had the same issue after updating to Catalina but restarting fixes it for me. Closing the issue and thanks for inputs.

**Closed by yajra** 2019-11-05 01:56 UTC
Labels: OCI_CRED_EXT, need feedback, need help

**Comment by cbj4074** [comment] 2019-12-16 21:16
This error can also occur when debugging with `phpdbg` if `ORACLE_HOME` is not set appropriately within the execution environment.

The solution appears to be to pass an appropriate value to the CLI executable, e.g., `ORACLE_HOME="/usr/lib/oracle/12.2/client64"`.

**Comment by rizama** [comment] 2020-11-25 02:26
similiar problem, but my problem solved by restarting my php using `service php-fpm restart`  ([full syntax](https://www.cyberciti.biz/faq/unix-linux-restart-php-service-command/)) because driver oci8 has not detected by php..

**Comment by nowen21** [comment] 2021-02-12 18:52
Buena apreciados parte de la solución la encontré en el siguiente link: https://stackoverflow.com/questions/41632584/c-wamp64-bin-php-php7-0-10-ext-php-oci8-12c-dll-1-is-not-a-valid-win32-app/46761211 y las librerías .dll van de acuerdo a la versión del php que se encuentra en el siguiente link: https://pecl.php.net/package/oci8/2.2.0/windows;  en mi caso utilicé: 7.4 Thread Safe (TS) x64. Espero haber contribuido en la solución que me llevó casi una semana encontrarla. Saludos desde Colombia

**Comment by JPdiedhiou** [comment] 2021-02-13 13:10
Hello dear,
Thank you for this solution. I think it will always help.
Best regards

Cordialement DIEDHIOU Jean Pierre
[cid:003c5f9c-6ee9-476b-80b4-2584f2cab049]
Founder & Ceo Digital Passion
Developper | Digital Referent | Graphic Designer
Tel: +221 77 233 90 37 / 76 027 19 16
diedhioujp@outlook.com | digital@digitalpassion.io
https://www.digitalpassion.io
________________________________
De : Ing José Dúmar Jiménez Ruíz <notifications@github.com>
Envoyé : vendredi 12 février 2021 18:52
À : yajra/laravel-oci8 <laravel-oci8@noreply.github.com>
Cc : Ghost_man <diedhioujp@outlook.com>; Mention <mention@noreply.github.com>
Objet : Re: [yajra/laravel-oci8] Use of undefined constant OCI_CRED_EXT - assumed 'OCI_CRED_EXT' (this will throw an Error in a future version of PHP) (#506)


Buena apreciados parte de la solución la encontré en el siguiente link: https://stackoverflow.com/questions/41632584/c-wamp64-bin-php-php7-0-10-ext-php-oci8-12c-dll-1-is-not-a-valid-win32-app/46761211 y las librerías .dll van de acuerdo a la versión del php que se encuentra en el siguiente link: https://pecl.php.net/package/oci8/2.2.0/windows; en mi caso utilicé: 7.4 Thread Safe (TS) x64. Espero haber contribuido en la solución que me llevó casi una semana encontrarla. Saludos desde Colombia

**Comment by shafiqruslan** [comment] 2021-05-04 16:38
I'm having the same problem on my intel mac Big Sur. Did anyone fix it?

**Comment by cbj4074** [comment] 2021-05-04 16:48
@shafiqruslan There's nothing to "fix". The OCI8 extension is not registered with PHP correctly, so you need to troubleshoot the reason for that.

I suggest reading [my earlier post](https://github.com/yajra/laravel-oci8/issues/506#issuecomment-566246990) carefully. Check your `phpinfo()` output, and if the OCI8 extension is not listed, check the potential causes that I noted.

**Comment by shafiqruslan** [comment] 2021-05-04 21:36
> @shafiqruslan There's nothing to "fix". The OCI8 extension is not registered with PHP correctly, so you need to troubleshoot the reason for that.
> 
> I suggest reading [my earlier post](https://github.com/yajra/laravel-oci8/issues/506#issuecomment-566246990) carefully. Check your `phpinfo()` output, and if the OCI8 extension is not listed, check the potential causes that I noted.

Hi, i have a question. i just found php.ini in my computer but not others that ini u mention 😅. Can i know where to locate it? In my phpinfo(), it listed oci8.

**Comment by einnar82** [comment] 2021-07-05 01:37
Hello,

It seems that the **OCI_CRED_EXT** constant is not allowed in the future release of PHP.
My workaround is to override the **OracleConnector** and **Oci8ServiceProvider** of the existing package.
Please see my gist file [here](https://gist.github.com/einnar82/d8eb7588bc25c01a2248717644972370).

Make sure that you will declare the **App\Providers\Oci8ServiceProvider** into the **config/app.php**

![image](https://user-images.githubusercontent.com/23412411/124406663-8ad39900-dd74-11eb-81de-818f94fcc2cb.png)

I hope it helps anyone else.
Thanks!
